# Generated by Django 4.2.25 on 2025-10-13 13:32

from django.db import migrations, models
import django.db.models.deletion
import files.models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FileContent',
            fields=[
                ('content_hash', models.CharField(max_length=64, primary_key=True, serialize=False, unique=True)),
                ('file', models.FileField(upload_to=files.models.content_upload_path)),
                ('size', models.BigIntegerField()),
                ('reference_count', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='File',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('original_filename', models.CharField(max_length=255)),
                ('file_type', models.CharField(max_length=100)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('file_content', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='files', to='files.filecontent')),
            ],
            options={
                'ordering': ['-uploaded_at'],
            },
        ),
    ]
