# Generated by Django 4.2.25 on 2025-10-13 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0002_storagesavingssummary_deduplicationevent'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='storagesavingssummary',
            options={'ordering': ['-period_start'], 'verbose_name_plural': 'Storage Savings Summaries'},
        ),
        migrations.AlterField(
            model_name='storagesavingssummary',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='storagesavingssummary',
            name='unique_files_shared',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterUniqueTogether(
            name='storagesavingssummary',
            unique_together={('period_start', 'period_end')},
        ),
        migrations.RemoveField(
            model_name='storagesavingssummary',
            name='total_storage_saved_gb',
        ),
        migrations.RemoveField(
            model_name='storagesavingssummary',
            name='total_storage_saved_mb',
        ),
    ]
